site_name: Vlad Balin's Blog
site_description: an example blog set up following the tutorial
site_url: http://www.example.com

theme:
  name: material

plugins:
  - search
  - blog:
      blog_dir: . 